# Generated by Django 5.2.1 on 2026-06-30 07:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_session_student_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('course_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('certificate_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_card_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admit_card_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Due', max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_records', to='students.student')),
            ],
        ),
    ]
