# Generated by Django 5.2.1 on 2026-06-30 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Deposit', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='deposit_documents/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
