# Generated by Django 5.2.1 on 2026-07-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_companydeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Due', 'Due')], default='Due', max_length=20),
        ),
    ]
