# Generated by Django 5.0.6 on 2026-06-29 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, help_text='Auto-generated full session timestamp', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=15),
        ),
    ]
