# Generated by Django 5.0.6 on 2026-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_batch_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='authority_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='authority_signature',
            field=models.ImageField(blank=True, null=True, upload_to='authority/signatures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_admission_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_birth_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_marksheet_photocopy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_nid_photocopy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_passport_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_signature',
            field=models.ImageField(blank=True, null=True, upload_to='students/signatures/'),
        ),
    ]
