# Generated by Django 5.2.1 on 2026-07-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='board_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examination',
        ),
    ]
