# Generated by Django 5.0.6 on 2026-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_board_name_remove_student_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='board_name',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Cumilla', 'Cumilla'), ('Jashore', 'Jashore'), ('Mymensingh', 'Mymensingh'), ('Madrasah', 'Madrasah'), ('Technical', 'Technical'), ('DIBS', 'DIBS (Dhaka)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='examination',
            field=models.CharField(blank=True, choices=[('PSC', 'Primary School Certificate (PSC)'), ('Ebtedayee', 'Ebtedayee'), ('JSC', 'Junior School Certificate (JSC)'), ('JDC', 'Junior Dakhil Certificate (JDC)'), ('SSC', 'Secondary School Certificate (SSC)'), ('Dakhil', 'Dakhil'), ('SSC_Vocational', 'SSC (Vocational)'), ('HSC', 'Higher Secondary Certificate (HSC)'), ('Alim', 'Alim'), ('HSC_Vocational', 'HSC (Vocational)'), ('HSC_BM', 'HSC (Business Management)'), ('Diploma', 'Diploma in Engineering'), ('Degree', 'Degree (Pass)'), ('Honours', 'Honours'), ('Masters', 'Masters')], max_length=50, null=True),
        ),
    ]
