# Generated by Django 5.0.6 on 2026-07-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_board_name_student_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='examination',
            field=models.CharField(blank=True, choices=[('SSC', 'Secondary School Certificate (SSC)'), ('Dakhil', 'Dakhil'), ('SSC_Vocational', 'SSC (Vocational)'), ('HSC', 'Higher Secondary Certificate (HSC)'), ('Alim', 'Alim'), ('HSC_Vocational', 'HSC (Vocational)'), ('HSC_BM', 'HSC (Business Management)'), ('Diploma', 'Diploma in Engineering'), ('Degree', 'Degree (Pass)'), ('Honours', 'Honours'), ('Masters', 'Masters')], max_length=50, null=True),
        ),
    ]
