# Generated by Django 5.0.6 on 2026-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approve_sms',
            field=models.TextField(blank=True, default='প্রিয় [name], JBD IT-তে আপনার ভর্তি অ্যাপ্রুভ করা হয়েছে। আইডি: [id]।', null=True),
        ),
    ]
