# Generated by Django 5.0.6 on 2026-07-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_approve_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='approve_sms',
        ),
    ]
