# Generated by Django 5.0.6 on 2026-06-29 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Course Code')),
                ('default_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Course Fee')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number/Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course', verbose_name='Select Course')),
            ],
        ),
    ]
