# Generated by Django 5.0.6 on 2026-07-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Name'),
        ),
    ]
