# Generated by Django 5.0.6 on 2026-07-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.IntegerField(default=0, verbose_name='Duration (Months)'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Course Image'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50, verbose_name='Course Level'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_classes',
            field=models.IntegerField(default=0, verbose_name='Total Classes'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=0, verbose_name='Total Hours'),
        ),
    ]
