"""
Django settings for web_project project.

Generated by 'django-admin startproject' using Django 5.0.
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

from .template import TEMPLATE_CONFIG, THEME_LAYOUT_DIR, THEME_VARIABLES

# Environment variables লোড করা হচ্ছে (.env ফাইল থেকে)
load_dotenv()

# Project Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Security Settings
SECRET_KEY = os.environ.get("SECRET_KEY", default="django-insecure-your-fallback-secret-key-here")
DEBUG = os.environ.get("DEBUG", "True").lower() in ["true", "yes", "1"]

ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "jbdit.bd", "www.jbdit.bd"]








# Current Environment Configuration
ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", default="local")
BASE_URL = os.environ.get("BASE_URL", default="http://127.0.0.1:8000")


# Application Definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',

    # Custom Internal Apps
    "apps.sample",
    "apps.pages",
    "apps.courses",
    "apps.account",  # কাস্টম ইউজার অ্যাকাউন্ট অ্যাপ
    "apps.front_pages",
    "apps.students",
    "apps.finance",


]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Static ফাইল হ্যান্ডেল করার জন্য
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # i18n ল্যাঙ্গুয়েজ সাপোর্টের জন্য
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# Template Configuration
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",

        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Custom Context Processors
                "config.context_processors.language_code",
                "config.context_processors.my_setting",
                "config.context_processors.get_cookie",
                "config.context_processors.environment",
            ],
            "libraries": {
                "theme": "web_project.template_tags.theme",
            },
            "builtins": [
                "django.templatetags.static",
                "web_project.template_tags.theme",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database Configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite33",
    }
}


# Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization (i18n & l10n)
LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("ar", _("Arabic")),
    ("de", _("German")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static Files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "src" / "assets",
]


# Default Primary Key Field Type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom Template & Theme Variables Mapping
THEME_LAYOUT_DIR = THEME_LAYOUT_DIR
TEMPLATE_CONFIG = TEMPLATE_CONFIG
THEME_VARIABLES = THEME_VARIABLES

# Custom User Model Configuration

AUTH_USER_MODEL = "account.Account"
LOGIN_URL = 'login'          # লগইন পাথের নাম (name="login")
LOGIN_REDIRECT_URL = 'dashboard_redirect'  # 👑 আপনার ডাইনামিক রাউটার ভিউ অনুযায়ী আপডেট করা হলো
