# Generated by Django 5.0.6 on 2026-07-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Visitor's Name")),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('visiting_date', models.DateField(verbose_name='Visiting Date')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='marketing.visitorcategory', verbose_name='Visiting Purpose Category')),
            ],
        ),
    ]
