# Generated by Django 5.0.6 on 2026-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, default='My Institute Portal Layout', max_length=255, null=True)),
                ('send_id_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_sms', models.TextField(blank=True, default='প্রিয় [name], JBD IT-তে আপনাকে স্বাগতম! পোর্টালে লগইন করতে ব্যবহার করুন Username: [phone] এবং Password: [phone]', null=True)),
                ('student_sms', models.TextField(blank=True, default='প্রিয় [name], JBD IT-তে আপনাকে স্বাগতম! পোর্টালে লগইন করতে ব্যবহার করুন Username: [phone] এবং Password: [phone]', null=True)),
                ('approve_sms', models.TextField(blank=True, null=True, verbose_name='Student Approval Confirmation SMS')),
                ('payment_sms', models.TextField(blank=True, default='প্রিয় [name], আপনার পেমেন্ট সফলভাবে সম্পন্ন হয়েছে। রশিদ নং: [invoice], পরিশোধিত টাকা: [amount]/-। ধন্যবাদ!', null=True, verbose_name='Student Payment Confirmation SMS')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, default='JBDIT', max_length=250, null=True)),
                ('email', models.EmailField(blank=True, default='JBDIT@gmail.com', max_length=100, null=True)),
                ('post_office', models.CharField(blank=True, default='JBDIT', max_length=101, null=True)),
                ('upozila', models.CharField(blank=True, default='JBDIT', max_length=100, null=True)),
                ('district', models.CharField(blank=True, default='Rajshahi', max_length=100, null=True)),
                ('eiin', models.CharField(blank=True, max_length=20, null=True)),
                ('school_code', models.CharField(blank=True, max_length=50, null=True)),
                ('established_at', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('map_link', models.URLField(blank=True, max_length=500, null=True)),
                ('friday', models.BooleanField(default=True, verbose_name='Friday')),
                ('saturday', models.BooleanField(default=True, verbose_name='Saturday')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/logo_fav/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/logo_fav/')),
                ('student_admission_pdf_banner', models.ImageField(blank=True, null=True, upload_to='pdf/banners/')),
                ('invoice_pdf_banner', models.ImageField(blank=True, null=True, upload_to='pdf/banners/')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sms_type', models.CharField(choices=[('registration', 'Registration Welcome'), ('approval', 'Admission Approval')], default='registration', max_length=20)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
