# Generated by Django 5.0.6 on 2026-07-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='JBDIT@gmail.com', max_length=105, null=True),
        ),
    ]
