# Generated by Django 5.0.6 on 2026-07-02 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutesetting',
            name='send_id_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institutesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutesetting',
            name='website_name',
            field=models.CharField(blank=True, default='My Institute Portal Layout', max_length=255, null=True),
        ),
    ]
