# Generated by Django 5.0.6 on 2026-07-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_institutesetting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutesetting',
            name='send_id_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
