# Generated by Django 5.0.6 on 2026-07-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_institutesetting_send_id_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstituteSetting',
            new_name='attendenceSetting',
        ),
    ]
