# Generated by Django 5.0.6 on 2026-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_rename_institutesetting_attendencesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencesetting',
            name='reg_sms',
            field=models.TextField(blank=True, default='Dear [name], Welcome to our institute! Use Username: [phone] and Password: [phone] to login to your portal.', null=True),
        ),
    ]
