# Generated by Django 5.0.6 on 2026-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_attendencesetting_reg_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencesetting',
            name='reg_sms',
            field=models.TextField(blank=True, default='প্রিয় [name], JBD IT-তে আপনাকে স্বাগতম! পোর্টালে লগইন করতে ব্যবহার করুন Username: [phone] এবং Password: [phone]', null=True),
        ),
    ]
