# Generated by Django 5.0.6 on 2026-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_alter_attendencesetting_reg_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencesetting',
            name='approve_sms',
            field=models.TextField(blank=True, null=True, verbose_name='Student Approval Confirmation SMS'),
        ),
    ]
