# Generated by Django 5.0.6 on 2026-07-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_white', models.CharField(blank=True, help_text='Example: Build Real Projects', max_length=255, null=True)),
                ('title_colored', models.CharField(blank=True, help_text='Example: For Your Portfolio', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Slider main paragraph text', null=True)),
                ('btn1_text', models.CharField(blank=True, help_text='Example: See Curriculum', max_length=50, null=True)),
                ('btn1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('btn2_text', models.CharField(blank=True, help_text='Example: Student Stories', max_length=50, null=True)),
                ('btn2_url', models.CharField(blank=True, max_length=500, null=True)),
                ('right_image', models.ImageField(blank=True, help_text='Right side graphical showcase image', null=True, upload_to='sliders/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
