# Generated by Django 5.0.6 on 2026-07-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_white', models.CharField(blank=True, help_text='Example: Building Careers,', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Main description paragraph text', null=True)),
                ('btn_text', models.CharField(blank=True, help_text='Example: Learn More', max_length=50, null=True)),
                ('btn_url', models.CharField(blank=True, max_length=500, null=True)),
                ('right_image', models.ImageField(blank=True, help_text='Background or Section Image', null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
    ]
