# Generated by Django 5.0.6 on 2026-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_pages', '0004_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, help_text='সেকশনের মেইন টাইটেল', max_length=200, null=True)),
                ('section_description', models.TextField(blank=True, help_text='সেকশনের বিবরণ', null=True)),
                ('image', models.ImageField(blank=True, help_text='বক্সের ছবি', null=True, upload_to='card_images/')),
                ('title', models.CharField(blank=True, help_text='বক্সের টাইটেল', max_length=200, null=True)),
                ('title_color', models.CharField(default='#000000', help_text='HEX বা Color Name (যেমন: #ff0000 বা red)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='বক্সের বিবরণ', null=True)),
                ('button_link', models.URLField(blank=True, help_text='খালি রাখলে সিঙ্গেল পেজে নিয়ে যাবে', null=True)),
            ],
        ),
    ]
