# Generated by Django 5.0.6 on 2026-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_pages', '0005_carditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL Slug (খালি রাখলে অটো জেনারেট হবে)', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='button_link',
            field=models.URLField(blank=True, help_text='খালি রাখলে সিঙ্গেল পেজে নিয়ে যাবে', null=True),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='description',
            field=models.TextField(blank=True, help_text='কোর্স বিবরণ', null=True),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='image',
            field=models.ImageField(blank=True, help_text='কোর্স ছবি', null=True, upload_to='card_images/'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='title',
            field=models.CharField(blank=True, help_text='কোর্স টাইটেল', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='title_color',
            field=models.CharField(default='#000000', help_text='HEX বা Color Name', max_length=20),
        ),
    ]
