# Generated by Django 5.0.6 on 2026-07-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_pages', '0006_carditem_slug_alter_carditem_button_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcontent',
            old_name='btn_text',
            new_name='left_btn_text',
        ),
        migrations.RenameField(
            model_name='aboutcontent',
            old_name='btn_url',
            new_name='left_btn_url',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='title_white',
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='left_description',
            field=models.TextField(blank=True, help_text='Left Section Description', null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='left_title',
            field=models.CharField(blank=True, help_text='Left Section Title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='left_title_color',
            field=models.CharField(blank=True, help_text='Example: #FFFFFF or white', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='right_btn_text',
            field=models.CharField(blank=True, help_text='Example: Contact Us', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='right_btn_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='right_description',
            field=models.TextField(blank=True, help_text='Right Section Description', null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='right_title',
            field=models.CharField(blank=True, help_text='Right Section Title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='right_title_color',
            field=models.CharField(blank=True, help_text='Example: #FF0000 or red', max_length=50, null=True),
        ),
    ]
