# Generated by Django 5.0.6 on 2026-07-22 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_pages', '0007_rename_btn_text_aboutcontent_left_btn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontent',
            name='left_btn_text',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='left_btn_url',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='left_description',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='left_title',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='left_title_color',
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='right_image',
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='right_btn_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='right_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='right_title',
            field=models.CharField(blank=True, help_text='Right Side Main Title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='right_title_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Card Title', max_length=255, null=True)),
                ('title_color', models.CharField(blank=True, default='#FFFFFF', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Card Description', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='front_pages.aboutcontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
