# Generated by Django 5.0.6 on 2026-07-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='মোবাইল নম্বর')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='ওটিপি কোড')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='তৈরির সময়')),
                ('is_used', models.BooleanField(blank=True, default=False, null=True, verbose_name='ব্যবহার করা হয়েছে?')),
            ],
            options={
                'verbose_name': 'SMS ভেরিফিকেশন',
                'verbose_name_plural': 'SMS ভেরিফিকেশনসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
